[build]
  publish = "BlazorWASM/bin/Release/net6.0/publish/wwwroot"
  command = "dotnet publish -c Release"

[context.production]
  command = "dotnet publish -c Release --output build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
